version: '3.8'
volumes:
  data:
services:
  db:
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  short_url:
    build: .
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - .:/app
    env_file:
      - short_url.env